name: ec_senior
description: EldersConnect app for Seniors
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  google_sign_in: ^4.0.14
  firebase_core: ^0.4.2+1
  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.12.10+2
  provider: ^3.1.0+1
  qr_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true