name: ec_senior
description: EldersConnect app for Seniors
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.0.0
  cloud_firestore: ^0.13.4+2
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.4+3
  flutter_auth_buttons: ^0.8.0
  google_sign_in: ^4.4.1
  qr_flutter: ^3.2.0
  shared_preferences: ^0.5.6+3
  firebase_database: ^3.1.6
  carousel_pro: ^1.0.0
  flutter_multi_carousel: ^1.0.0
  carousel_slider: ^1.3.0
  carousel_widget: ^0.1.1
  url_launcher: ^5.4.11
  contacts_service: ^0.4.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon/icon-adaptive.png'
  adaptive_icon_background: '#ffc107'

  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter:
  uses-material-design: true

  assets:
     - assets/graphics/
     - assets/icon/

  fonts:
    - family: LexendDeca
      fonts:
        - asset: assets/fonts/LexendDeca/LexendDeca-Regular.ttf